# fly.toml app configuration file generated for ndc-challenge-blog on 2023-06-15T00:20:12+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ndc-challenge-blog"
primary_region = "nrt"
console_command = "/code/manage.py shell"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0

[[statics]]
  guest_path = "/code/staticfiles"
  url_prefix = "/static/"
